using System.Text.Json.Serialization;

namespace Tally.Contracts.Ingest;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow)]
[JsonSerializable(typeof(IngestVersions))]
[JsonSerializable(typeof(IngestOutcomeCounts))]
[JsonSerializable(typeof(ReconciliationControl))]
[JsonSerializable(typeof(ReconciliationSummary))]
[JsonSerializable(typeof(ManifestApprovalState))]
[JsonSerializable(typeof(PreviewImportInput))]
[JsonSerializable(typeof(PreviewImportResult))]
[JsonSerializable(typeof(InspectManifestInput))]
[JsonSerializable(typeof(InspectManifestResult))]
[JsonSerializable(typeof(ApproveManifestInput))]
[JsonSerializable(typeof(ApproveManifestResult))]
[JsonSerializable(typeof(CommitBatchInput))]
[JsonSerializable(typeof(ResumeBatchInput))]
[JsonSerializable(typeof(IngestStatusInput))]
[JsonSerializable(typeof(IngestStatusResult))]
[JsonSerializable(typeof(AbandonBatchInput))]
[JsonSerializable(typeof(AbandonBatchResult))]
[JsonSerializable(typeof(CleanupBatchInput))]
[JsonSerializable(typeof(CleanupBatchResult))]
[JsonSerializable(typeof(IngestError))]
[JsonSerializable(typeof(BatchStatusSummary))]
[JsonSerializable(typeof(BatchStatusDetail))]
[JsonSerializable(typeof(StatementPeriod))]
[JsonSerializable(typeof(ImportProvenance))]
[JsonSerializable(typeof(ImportBatch))]
[JsonSerializable(typeof(ManifestRevision))]
[JsonSerializable(typeof(SourceRecordOutcome))]
[JsonSerializable(typeof(ImportCandidate))]
[JsonSerializable(typeof(ManifestApproval))]
[JsonSerializable(typeof(ImportReceiptCounts))]
[JsonSerializable(typeof(CandidateReceipt))]
[JsonSerializable(typeof(ImportReceipt))]
[JsonSerializable(typeof(CompletedMetadataReceipt))]
[JsonSerializable(typeof(FrozenLedgerRecordRequest))]
[JsonSerializable(typeof(LedgerImmutableVerification))]
public partial class IngestJsonContext : JsonSerializerContext;
