using System.Text.Json.Serialization;
using Tally.Contracts.Classify.Evidence;
using Tally.Contracts.Classify.Operations;
using Tally.Contracts.Classify.Rules;
using Tally.Contracts.Common;
using Tally.Infrastructure.Classify.Corpus;

namespace Tally.Contracts.Classify;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow)]
[JsonSerializable(typeof(ClassifyEvaluateRequest))]
[JsonSerializable(typeof(ClassifyEvaluateResult))]
[JsonSerializable(typeof(ClassifyOutcomeGetRequest))]
[JsonSerializable(typeof(ClassifyOutcomeGetResult))]
[JsonSerializable(typeof(ClassifyConflictRuleProposal))]
[JsonSerializable(typeof(ClassifyConflictRuleProposal[]))]
[JsonSerializable(typeof(ClassifyApplyPreviewRequest))]
[JsonSerializable(typeof(ClassifyApplyPreviewResult))]
[JsonSerializable(typeof(ClassifyApplyRunRequest))]
[JsonSerializable(typeof(ClassifyApplyRunResult))]
[JsonSerializable(typeof(ClassifyApplyItemResult))]
[JsonSerializable(typeof(ClassifyApplySelection))]
[JsonSerializable(typeof(ClassifyExplicitCorrectionItem))]
[JsonSerializable(typeof(ClassifyRuleSaveRequest))]
[JsonSerializable(typeof(ClassifyRuleSaveResult))]
[JsonSerializable(typeof(ClassifyRuleValidateRequest))]
[JsonSerializable(typeof(ClassifyRuleValidateResult))]
[JsonSerializable(typeof(ClassifyRuleActivateRequest))]
[JsonSerializable(typeof(ClassifyRuleActivateResult))]
[JsonSerializable(typeof(ClassifyRuleRetireRequest))]
[JsonSerializable(typeof(ClassifyRuleRetireResult))]
[JsonSerializable(typeof(ClassifyFeedbackRecordRequest))]
[JsonSerializable(typeof(ClassifyFeedbackRecordResult))]
[JsonSerializable(typeof(ClassifyStatusRequest))]
[JsonSerializable(typeof(ClassifyStatusResult))]
[JsonSerializable(typeof(ClassifyRuleStatusDetail))]
[JsonSerializable(typeof(ClassifyRuleStatusVersion))]
[JsonSerializable(typeof(ClassifyRuleStatusVersion[]))]
[JsonSerializable(typeof(ClassifyValidationStatusDetail))]
[JsonSerializable(typeof(ClassifyEvaluationStatusDetail))]
[JsonSerializable(typeof(ClassifyPreviewStatusDetail))]
[JsonSerializable(typeof(ClassifyApplyStatusDetail))]
[JsonSerializable(typeof(ClassifyFeedbackStatusDetail))]
[JsonSerializable(typeof(ClassifyAbandonmentStatusDetail))]
[JsonSerializable(typeof(ClassifyCleanupStatusDetail))]
[JsonSerializable(typeof(ClassifyAbandonRequest))]
[JsonSerializable(typeof(ClassifyAbandonResult))]
[JsonSerializable(typeof(ClassifyCleanupRequest))]
[JsonSerializable(typeof(ClassifyCleanupResult))]
[JsonSerializable(typeof(ClassificationRuleConditionInput))]
[JsonSerializable(typeof(ClassificationRuleConditionInput[]))]
[JsonSerializable(typeof(ClassificationRuleVersionDetail))]
[JsonSerializable(typeof(ClassificationNormalizationDescriptor))]
[JsonSerializable(typeof(ClassificationFieldDescriptor))]
[JsonSerializable(typeof(ClassificationPredicateDescriptor))]
[JsonSerializable(typeof(ClassificationRuleVocabularyCatalogue))]
[JsonSerializable(typeof(ClassificationRuleFieldKey))]
[JsonSerializable(typeof(ClassificationRulePredicateKind))]
[JsonSerializable(typeof(ClassificationAmountDirectionValue))]
[JsonSerializable(typeof(ClassifyApplySelectionMode))]
[JsonSerializable(typeof(ClassifyStatusSubjectType))]
[JsonSerializable(typeof(ClassifyFeedbackDecision))]
[JsonSerializable(typeof(ClassifyOutcomeKind))]
[JsonSerializable(typeof(ClassifyApplyItemResultKind))]
// Operator ergonomics additive contracts (bd-1gly) — types only; no descriptors yet.
[JsonSerializable(typeof(ClassifyOutcomeListRequest))]
[JsonSerializable(typeof(ClassifyOutcomeListResult))]
[JsonSerializable(typeof(ClassifyOutcomeListItem))]
[JsonSerializable(typeof(ClassifyOutcomeListItem[]))]
[JsonSerializable(typeof(ClassifyRuleListRequest))]
[JsonSerializable(typeof(ClassifyRuleListResult))]
[JsonSerializable(typeof(ClassifyRuleListItem))]
[JsonSerializable(typeof(ClassifyRuleListItem[]))]
[JsonSerializable(typeof(ClassifyRuleSetActiveGetRequest))]
[JsonSerializable(typeof(ClassifyRuleSetActiveGetResult))]
[JsonSerializable(typeof(ClassifyActiveRuleSetCategory))]
[JsonSerializable(typeof(ClassifyActiveRuleSetCategory[]))]
[JsonSerializable(typeof(ClassifyCorpusBuildRequest))]
[JsonSerializable(typeof(ClassifyCorpusBuildResult))]
[JsonSerializable(typeof(ClassifyCorpusBuildLabel))]
[JsonSerializable(typeof(ClassifyCorpusBuildLabel[]))]
[JsonSerializable(typeof(ClassifyCorpusBuildProjectionEnvelope))]
[JsonSerializable(typeof(ClassifyCorpusBuildProjectionItem))]
[JsonSerializable(typeof(ClassifyCorpusBuildProjectionItem[]))]
[JsonSerializable(typeof(ClassifyUnresolvedReportRequest))]
[JsonSerializable(typeof(ClassifyUnresolvedReportResult))]
[JsonSerializable(typeof(ClassifyUnresolvedPatternGroup))]
[JsonSerializable(typeof(ClassifyUnresolvedPatternGroup[]))]
[JsonSerializable(typeof(ClassifyOutcomeStaleFilter))]
[JsonSerializable(typeof(ClassifyRuleLifecycleFilter))]
[JsonSerializable(typeof(ClassifyRuleProvenanceKind))]
[JsonSerializable(typeof(ClassifyCategoryLifecycleState))]
[JsonSerializable(typeof(OperationLimits))]
[JsonSerializable(typeof(VerifiedOwnerRulebookGateReceipt))]
[JsonSerializable(typeof(OwnerRulebookGateInputManifest))]
[JsonSerializable(typeof(OwnerBenefitEvidenceReceipt))]
[JsonSerializable(typeof(string[]))]
public partial class ClassifyJsonContext : JsonSerializerContext;
