using System.Runtime.Versioning;
using System.Text.Json;
using Tally.Bootstrap;
using Tally.Cli;
using Tally.Contracts.Common;
using Tally.Contracts.Ledger.Categories;
using Tally.Contracts.Ledger.Dimensions;
using Tally.Domain.Ledger;
using Tally.Features.Ledger.Categories;
using Tally.Infrastructure.Storage;
using Xunit;

namespace Tally.Tests.Features.Ledger.Categories;

[SupportedOSPlatform("linux")]
public sealed class CategoryOperationTests : IAsyncLifetime
{
    private readonly string root = Path.Combine(Path.GetTempPath(), $"tally-category-{Guid.NewGuid():N}");
    private TallyProcess process = null!;

    [Fact] public void Registry_exposes_seven_typed_operations() { var r = OperationRegistry.Create(); Assert.Equal(73, r.Descriptors.Count); Assert.Equal(typeof(ReparentCategoryInput), r.Find("ledger.category.reparent")!.RequestTypeInfo.Type); Assert.Equal(typeof(CategoryReparentResult), r.Find("ledger.category.reparent")!.ResultTypeInfo.Type); }
    [Fact] public async Task Root_and_child_creation_return_stable_ancestry() { var root = Detail(await Create("Root", null, "root")); var child = Detail(await Create("Child", root.CategoryId, "child")); Assert.Equal(0, root.Depth); Assert.Equal([root.CategoryId], root.AncestryIds); Assert.Equal(1, child.Depth); Assert.Equal([root.CategoryId, child.CategoryId], child.AncestryIds); }
    [Fact] public async Task Duplicate_names_are_rejected_only_among_active_siblings() { var a = Detail(await Create("Food", null, "a")); AssertError(await Create(" food ", null, "b"), 5, CategoryErrors.DuplicateSibling); var parent = Detail(await Create("Other", null, "c")); Assert.Equal("Food", Detail(await Create("Food", parent.CategoryId, "d")).Name); await Archive(a.CategoryId, "old", "e"); Assert.Equal("Food", Detail(await Create("Food", null, "f")).Name); }
    [Fact] public async Task Rename_preserves_identity_parent_and_children() { var root = Detail(await Create("Root", null, "a")); var child = Detail(await Create("Child", root.CategoryId, "b")); var renamed = Lifecycle(await Rename(root.CategoryId, "Household", "clear", "c")); var fetched = Detail(await Get(child.CategoryId, true)); Assert.Equal(root.CategoryId, renamed.Category.CategoryId); Assert.Equal(root.CategoryId, fetched.ParentCategoryId); Assert.Equal(2, renamed.Category.LifecycleHistory.Count); }
    [Fact] public async Task Reparent_appends_history_and_changes_current_ancestry() { var a = Detail(await Create("A", null, "a")); var b = Detail(await Create("B", null, "b")); var c = Detail(await Create("C", a.CategoryId, "c")); var moved = Reparented(await Reparent(c.CategoryId, b.CategoryId, "move", "d")); Assert.Equal(c.CategoryId, moved.Category.CategoryId); Assert.Equal([b.CategoryId, c.CategoryId], moved.Category.AncestryIds); Assert.Equal(2, moved.Category.ParentHistory.Count); }
    [Fact] public async Task Self_parent_and_descendant_cycle_fail_without_mutation() { var root = Detail(await Create("Root", null, "a")); var child = Detail(await Create("Child", root.CategoryId, "b")); AssertError(await Reparent(root.CategoryId, root.CategoryId, "self", "c"), 3, CategoryErrors.SelfParent); AssertError(await Reparent(root.CategoryId, child.CategoryId, "cycle", "d"), 6, CategoryErrors.Cycle); Assert.Null(Detail(await Get(root.CategoryId, true)).ParentCategoryId); }
    [Fact] public async Task Archived_parent_and_target_reparent_fail() { var parent = Detail(await Create("Parent", null, "a")); var target = Detail(await Create("Target", null, "b")); await Archive(parent.CategoryId, "closed", "c"); AssertError(await Reparent(target.CategoryId, parent.CategoryId, "move", "d"), 6, CategoryErrors.ParentArchived); await Archive(target.CategoryId, "closed", "e"); AssertError(await Reparent(target.CategoryId, null, "move", "f"), 6, CategoryErrors.Archived); }
    [Fact] public async Task Active_child_blocks_archive_then_reactivation_preserves_identity() { var root = Detail(await Create("Root", null, "a")); var child = Detail(await Create("Child", root.CategoryId, "b")); AssertError(await Archive(root.CategoryId, "blocked", "c"), 6, CategoryErrors.ActiveChildren); await Archive(child.CategoryId, "closed", "d"); var archived = Lifecycle(await Archive(root.CategoryId, "closed", "e")); var active = Lifecycle(await Reactivate(root.CategoryId, "needed", "f")); Assert.Equal(archived.Category.CategoryId, active.Category.CategoryId); Assert.Equal(CategoryStatus.Active, active.Category.Status); }
    [Fact] public async Task Reactivation_requires_active_ancestry() { var root = Detail(await Create("Root", null, "a")); var child = Detail(await Create("Child", root.CategoryId, "b")); await Archive(child.CategoryId, "closed", "c"); await Archive(root.CategoryId, "closed", "d"); AssertError(await Reactivate(child.CategoryId, "needed", "e"), 6, CategoryErrors.AncestorArchived); }
    [Fact] public async Task List_children_subtree_and_all_are_deterministic() { var root = Detail(await Create("Root", null, "a")); await Create("B", root.CategoryId, "b"); await Create("A", root.CategoryId, "c"); var child = List(await ListCategories(new(null, root.CategoryId, CategoryListScope.Children))); var subtree = List(await ListCategories(new(null, root.CategoryId, CategoryListScope.Subtree))); Assert.Equal(["A", "B"], child.Items.Select(x => x.Name)); Assert.Equal(3, subtree.Items.Count); Assert.Equal(root.CategoryId, subtree.Items[0].CategoryId); Assert.Equal(child.Items.Select(x => x.CategoryId), List(await ListCategories(new(null, root.CategoryId, CategoryListScope.Children))).Items.Select(x => x.CategoryId)); }
    [Fact] public async Task Mutation_replay_is_stable_and_changed_replay_conflicts() { var first = Detail(await Create("Root", null, "same")); var replay = Detail(await Create("Root", null, "same")); Assert.Equal(first.CategoryId, replay.CategoryId); AssertError(await Create("Changed", null, "same"), 5, "LEDGER-IDEMPOTENCY-001"); }
    [Fact] public async Task Rename_reparent_archive_and_reactivate_replays_return_original_events() { var first = Detail(await Create("First", null, "a")); var second = Detail(await Create("Second", null, "b")); var rename = Lifecycle(await Rename(first.CategoryId, "Renamed", "why", "rename")); Assert.Equal(rename.LifecycleEventId, Lifecycle(await Rename(first.CategoryId, "Renamed", "why", "rename")).LifecycleEventId); var move = Reparented(await Reparent(first.CategoryId, second.CategoryId, "move", "move")); Assert.Equal(move.ParentEventId, Reparented(await Reparent(first.CategoryId, second.CategoryId, "move", "move")).ParentEventId); var archive = Lifecycle(await Archive(first.CategoryId, "old", "archive")); Assert.Equal(archive.LifecycleEventId, Lifecycle(await Archive(first.CategoryId, "old", "archive")).LifecycleEventId); var active = Lifecycle(await Reactivate(first.CategoryId, "back", "active")); Assert.Equal(active.LifecycleEventId, Lifecycle(await Reactivate(first.CategoryId, "back", "active")).LifecycleEventId); }
    [Fact] public async Task Get_history_is_explicit_and_unknown_is_stable() { var category = Detail(await Create("Root", null, "a")); await Rename(category.CategoryId, "Renamed", "why", "b"); Assert.Empty(Detail(await Get(category.CategoryId, false)).LifecycleHistory); Assert.Equal(2, Detail(await Get(category.CategoryId, true)).LifecycleHistory.Count); AssertError(await Get(LedgerId.New().ToString(), false), 4, CategoryErrors.NotFound); }
    [Fact] public async Task Category_creation_does_not_create_a_spend_pool() { await Create("Food", null, "a"); var result = await Run("ledger.pool.list", Json("{}"), null); Assert.Empty(Success(result, LedgerJsonContext.Default.SpendPoolListResult).Items); }

    public async Task InitializeAsync() { var db = await LedgerRuntimeBootstrap.InitializeCurrentAsync(root, CancellationToken.None); process = new(OperationRegistry.Create(), LedgerServices.Create(db)); }
    public Task DisposeAsync() { if (Directory.Exists(root)) Directory.Delete(root, true); return Task.CompletedTask; }
    private Task<ProcessResult> Create(string name, string? parent, string key) => Run("ledger.category.create", JsonSerializer.SerializeToElement(new CreateCategoryInput(name, parent), LedgerJsonContext.Default.CreateCategoryInput), key);
    private Task<ProcessResult> Get(string id, bool history) => Run("ledger.category.get", JsonSerializer.SerializeToElement(new GetCategoryInput(id, history), LedgerJsonContext.Default.GetCategoryInput), null);
    private Task<ProcessResult> Rename(string id, string name, string reason, string key) => Run("ledger.category.rename", JsonSerializer.SerializeToElement(new RenameCategoryInput(id, name, reason), LedgerJsonContext.Default.RenameCategoryInput), key);
    private Task<ProcessResult> Reparent(string id, string? parent, string reason, string key) => Run("ledger.category.reparent", JsonSerializer.SerializeToElement(new ReparentCategoryInput(id, parent, reason), LedgerJsonContext.Default.ReparentCategoryInput), key);
    private Task<ProcessResult> Archive(string id, string reason, string key) => Run("ledger.category.archive", JsonSerializer.SerializeToElement(new ArchiveCategoryInput(id, reason), LedgerJsonContext.Default.ArchiveCategoryInput), key);
    private Task<ProcessResult> Reactivate(string id, string reason, string key) => Run("ledger.category.reactivate", JsonSerializer.SerializeToElement(new ReactivateCategoryInput(id, reason), LedgerJsonContext.Default.ReactivateCategoryInput), key);
    private Task<ProcessResult> ListCategories(ListCategoriesInput input) => Run("ledger.category.list", JsonSerializer.SerializeToElement(input, LedgerJsonContext.Default.ListCategoriesInput), null);
    private async Task<ProcessResult> Run(string op, JsonElement input, string? key) { var body = JsonSerializer.Serialize(new RequestEnvelope("1.0", new("human", "category-test"), input, key), LedgerJsonContext.Default.RequestEnvelope); var args = OperationRegistry.Create().Find(op)!.CliPath.Split(' ').Skip(1).Concat(["--input", "-"]).ToArray(); return await process.RunAsync(args, body, CancellationToken.None); }
    private static JsonElement Json(string value) => JsonDocument.Parse(value).RootElement.Clone();
    private static CategoryDetail Detail(ProcessResult result) => Success(result, LedgerJsonContext.Default.CategoryDetail);
    private static CategoryLifecycleResult Lifecycle(ProcessResult result) => Success(result, LedgerJsonContext.Default.CategoryLifecycleResult);
    private static CategoryReparentResult Reparented(ProcessResult result) => Success(result, LedgerJsonContext.Default.CategoryReparentResult);
    private static CategoryListResult List(ProcessResult result) => Success(result, LedgerJsonContext.Default.CategoryListResult);
    private static T Success<T>(ProcessResult result, System.Text.Json.Serialization.Metadata.JsonTypeInfo<T> type) { Assert.Equal(0, result.ExitCode); var envelope = JsonSerializer.Deserialize(result.Stdout, LedgerJsonContext.Default.ResultEnvelope)!; return JsonSerializer.Deserialize(envelope.Result!.Value, type)!; }
    private static void AssertError(ProcessResult result, int exit, string code) { Assert.Equal(exit, result.ExitCode); Assert.Equal(code, JsonSerializer.Deserialize(result.Stdout, LedgerJsonContext.Default.ResultEnvelope)!.Error!.Code); }
}
